name: ${CONTAINER_NAME}
services:
    service:
        shm_size: 32gb
        user: ${CONTAINER_UID}:${CONTAINER_UID}
        build:
            context: ..
            dockerfile: .server/Dockerfile
            args:
                CONTAINER_USER: ${CONTAINER_USER}
                CONTAINER_UID: ${CONTAINER_UID}
                CONTAINER_HOME: ${CONTAINER_HOME}
                CONTAINER_WORK_DIR: ${CONTAINER_WORK_DIR}
        environment:
            CONTAINER_USER: ${CONTAINER_USER}
            CONTAINER_UID: ${CONTAINER_UID}
            CONTAINER_HOME: ${CONTAINER_HOME}
            CONTAINER_WORK_DIR: ${CONTAINER_WORK_DIR}
            CONTAINER_UV_GROUP: ${CONTAINER_UV_GROUP}
            TZ: ${TZ}
        volumes:
            - ../:${CONTAINER_WORK_DIR}
            - venv:${CONTAINER_WORK_DIR}/.venv
            - keys:${CONTAINER_WORK_DIR}/.keys:ro

            - uv_cache:${CONTAINER_HOME}/.cache/uv:rw
            - huggingface_cache:${CONTAINER_HOME}/.cache/huggingface
            - torch_cache:${CONTAINER_HOME}/.cache/torch
            - fasttext_cache:${CONTAINER_HOME}/.cache/fasttext
            - whisper_cache:${CONTAINER_HOME}/.cache/whisper
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ["${CONTAINER_GPU_ID}"]
                          capabilities: [gpu]
    nginx:
        image: nginx:latest
        ports:
            - ${HOST_PORT}:${CONTAINER_PORT}
        volumes:
            - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ../nginx/certbot/conf:/etc/letsencrypt/live
            - ../nginx/certbot/www:/var/www/certbot
        depends_on:
            - service

volumes:
    venv:
        driver: local
    keys:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${API_KEY_PATH}
    uv_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${CONTAINER_VOLUME}/cache/uv
    huggingface_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${CONTAINER_VOLUME}/cache/huggingface
    torch_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${CONTAINER_VOLUME}/cache/torch
    fasttext_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${CONTAINER_VOLUME}/cache/fasttext
    whisper_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${CONTAINER_VOLUME}/cache/whisper
