[project]
name = "dev"
version = "0.1.0"
description = "SilRok AI"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "alembic==1.16.4",
    "annotated-types==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "anyio==4.10.0",
    "asteroid-filterbanks==0.4.0",
    "async-timeout==5.0.1",
    "attrs==25.3.0",
    "audioread==3.0.1",
    "av==15.0.0",
    "beartype==0.21.0",
    "beautifulsoup4==4.13.4",
    "bidict==0.23.1",
    "bs4==0.0.2",
    "cachetools==5.5.2",
    "certifi==2025.8.3",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "cmudict==1.1.1",
    "coloredlogs==15.0.1",
    "colorlog==6.9.0",
    "contourpy==1.3.2",
    "cryptography==45.0.6",
    "ctranslate2==4.6.0",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "dependency-injector==4.48.1",
    "distance==0.1.3",
    "docopt==0.6.2",
    "einops==0.8.1",
    "emoji==1.2.0",
    "exceptiongroup==1.3.0",
    "fastapi==0.116.1",
    "faster-whisper==1.2.0",
    "filelock==3.18.0",
    "flatbuffers==25.2.10",
    "fonttools==4.59.0",
    "frozenlist==1.7.0",
    "fsspec==2025.7.0",
    "google-ai-generativelanguage==0.6.15",
    "google-api-core==2.25.1",
    "google-api-python-client==2.178.0",
    "google-auth==2.40.3",
    "google-auth-httplib2==0.2.0",
    "google-generativeai==0.8.5",
    "googleapis-common-protos==1.70.0",
    "greenlet==3.2.4",
    "grpcio==1.74.0",
    "grpcio-status==1.71.2",
    "h11==0.16.0",
    "hangul-jamo==1.0.1",
    "hf-xet==1.1.7",
    "hiredis==3.2.1",
    "httplib2==0.22.0",
    "httptools==0.6.4",
    "huggingface-hub==0.34.3",
    "humanfriendly==10.0",
    "hyperpyyaml==1.2.2",
    "idna==3.10",
    "importlib-metadata==8.7.0",
    "importlib-resources==6.5.2",
    "iniconfig==2.1.0",
    "jamo==0.4.1",
    "jinja2==3.1.6",
    "joblib==1.5.1",
    "jsonschema==4.25.0",
    "jsonschema-specifications==2025.4.1",
    "julius==0.2.7",
    "kiwisolver==1.4.8",
    "kollocate==0.0.2",
    "koparadigm==0.10.0",
    "kss==6.0.5",
    "lazy-loader==0.4",
    "librosa==0.11.0",
    "lightning==2.5.2",
    "lightning-utilities==0.15.2",
    "llvmlite==0.44.0",
    "loguru==0.7.3",
    "mako==1.3.10",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "more-itertools==10.7.0",
    "mpmath==1.3.0",
    "msgpack==1.1.1",
    "multidict==6.6.3",
    "networkx==3.4.2",
    "numba==0.61.2",
    "numpy==2.2.6",
    "nvidia-cublas-cu12==12.8.4.1",
    "nvidia-cuda-cupti-cu12==12.8.90",
    "nvidia-cuda-nvrtc-cu12==12.8.93",
    "nvidia-cuda-runtime-cu12==12.8.90",
    "nvidia-cudnn-cu12==9.10.2.21",
    "nvidia-cufft-cu12==11.3.3.83",
    "nvidia-cufile-cu12==1.13.1.3",
    "nvidia-curand-cu12==10.3.9.90",
    "nvidia-cusolver-cu12==11.7.3.90",
    "nvidia-cusparse-cu12==12.5.8.93",
    "nvidia-cusparselt-cu12==0.7.1",
    "nvidia-nccl-cu12==2.27.3",
    "nvidia-nvjitlink-cu12==12.8.93",
    "nvidia-nvtx-cu12==12.8.90",
    "omegaconf==2.3.0",
    "onnxruntime==1.22.1",
    "openai-whisper==20250625",
    "optuna==4.4.0",
    "packaging==25.0",
    "pandas==2.3.1",
    "pecab==1.0.8",
    "pillow==11.3.0",
    "platformdirs==4.3.8",
    "pluggy==1.6.0",
    "pooch==1.8.2",
    "primepy==1.3",
    "propcache==0.3.2",
    "proto-plus==1.26.1",
    "protobuf==5.29.5",
    "pyannote-audio==3.3.2",
    "pyannote-core==5.0.0",
    "pyannote-database==5.1.3",
    "pyannote-metrics==3.2.1",
    "pyannote-pipeline==3.0.1",
    "pyarrow==21.0.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pygments==2.19.2",
    "pyjwt==2.10.1",
    "pyparsing==3.2.3",
    "pysbd==0.3.4",
    "pytest==8.4.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "python-multipart==0.0.20",
    "pytorch-lightning==2.5.2",
    "pytorch-metric-learning==2.8.1",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "rapidfuzz==3.13.0",
    "ray==2.48.0",
    "redis==6.4.0",
    "referencing==0.36.2",
    "regex==2025.7.34",
    "requests==2.32.4",
    "rich==14.1.0",
    "rpds-py==0.27.0",
    "rsa==4.9.1",
    "ruamel-yaml==0.18.14",
    "ruamel-yaml-clib==0.2.12",
    "scikit-learn==1.7.1",
    "scipy==1.15.3",
    "semver==3.0.4",
    "sentencepiece==0.2.0",
    "setuptools==80.9.0",
    "shellingham==1.5.4",
    "silero-vad==5.1.2",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "soundfile==0.13.1",
    "soupsieve==2.7",
    "soxr==0.5.0.post1",
    "speechbrain==1.0.3",
    "sqlalchemy==2.0.42",
    "starlette==0.47.2",
    "sympy==1.14.0",
    "tabulate==0.9.0",
    "tensorboardx==2.6.4",
    "threadpoolctl==3.6.0",
    "tiktoken==0.10.0",
    "tokenizers==0.21.4",
    "tomli==2.2.1",
    "torch==2.8.0",
    "torch-audiomentations==0.12.0",
    "torch-pitch-shift==1.2.5",
    "torchaudio==2.8.0",
    "torchmetrics==1.8.0",
    "torchvision==0.23.0",
    "tossi==0.3.1",
    "tqdm==4.67.1",
    "triton==3.4.0",
    "typer==0.16.0",
    "typing-extensions==4.14.1",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "unidecode==1.4.0",
    "uritemplate==4.2.0",
    "urllib3==2.5.0",
    "uvicorn==0.35.0",
    "uvloop==0.21.0",
    "watchfiles==1.1.0",
    "websockets==15.0.1",
    "whoosh==2.7.4",
    "xlrd==1.2.0",
    "yarl==1.20.1",
    "zipp==3.23.0",
]

[dependency-groups]
dev = []
