[project]
name = "dev"
version = "0.1.0"
description = "SilRok AI"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "dependency-injector>=4.48.2",
    "fastapi>=0.121.0",
    "google-auth>=2.43.0",
    "google-cloud-aiplatform>=1.126.1",
    "LID",
    "numpy>=1.26.4",
    "python-multipart>=0.0.20",
    "sjaipy",
    "sjpy",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.4.10",
    "notebook>=7.4.7",
]

[tool.pytest.ini_options]
env_files=[".env"]

# [tool.setuptools.packages.find]
# where = ["."]
# include = ["LID*"]

[tool.uv.sources]
LID = { path = "modules/LID", editable = true }
sjaipy = { path = "modules/sjaipy", editable = true }
sjpy = { path = "modules/sjpy", editable = true }

