name: SilRokAI-Dev
services:
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        shm_size: "36gb"
        volumes:
            - ../:/workspaces/dev

            #   - ../.model/huggingface:/root/.cache/huggingface
            - F:/Models/huggingface:/home/vscode/.cache/huggingface
            #   - ../.model/torch:/root/.cache/torch
            - F:/Models/torch:/home/vscode/.cache/torch

            - C:/Env/python/Silrok-AI:/workspaces/dev/.venv
            # - /workspaces/dev/.venv # no cache
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        ports:
            - "8000:8000"
        command: ["tail", "-f", "/dev/null"]
