server {
    listen 80;
    server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
    }

    server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/fullchain.crt;
    ssl_certificate_key /etc/nginx/certs/privkey.key;

    location / {
        proxy_pass http://service:8000;
    }
}

